# Generated by Django 6.0.7 on 2026-07-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuota_inscripcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('premios', models.CharField(help_text='Ej. 70% al 1er lugar, 30% al 2do', max_length=200)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto para Inscripciones'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado')], default='Abierto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('imagen_portada', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.CharField(help_text='Ej. 8vos de Final, Gran Final', max_length=50)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Finalizada', 'Finalizada'), ('En Disputa', 'En Disputa')], default='Pendiente', max_length=20)),
                ('fecha_hora_programada', models.DateTimeField(blank=True, null=True)),
                ('estadisticas_detalladas', models.JSONField(blank=True, help_text='Formato JSON para kills, headshots, etc.', null=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_local', to='equipos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_visitante', to='equipos.equipo')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victorias', to='equipos.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='torneos.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_streaming', models.CharField(help_text='Ej. juan123', max_length=100)),
                ('plataforma', models.CharField(help_text='Ej. Twitch, Kick', max_length=50)),
                ('idioma', models.CharField(blank=True, help_text='Ej. Español', max_length=50, null=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmisiones', to='torneos.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='torneo',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='torneos', to='torneos.videojuego'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
                ('transaccion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='equipos.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'equipo')},
            },
        ),
    ]
