# Generated by Django 6.0.7 on 2026-08-07 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_equipo_logo_url_remove_miembroequipo_rol_and_more'),
        ('torneos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='transaccion_id',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='ganador',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de inscripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fichas_usadas',
            field=models.IntegerField(default=0, verbose_name='Fichas LeBrum usadas'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que pagó'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del torneo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='modalidad',
            field=models.CharField(choices=[('5v5', '5v5'), ('2v2', '2v2'), ('1v1', '1v1')], default='5v5', max_length=10, verbose_name='Modalidad del torneo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='equipos.equipo', verbose_name='Equipo inscrito'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.torneo', verbose_name='Torneo'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_local', to='equipos.equipo', verbose_name='Equipo local'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_visitante', to='equipos.equipo', verbose_name='Equipo visitante'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='estadisticas_detalladas',
            field=models.JSONField(blank=True, null=True, verbose_name='Estadísticas detalladas'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En curso'), ('Finalizada', 'Finalizada'), ('En Disputa', 'En disputa')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='fecha_hora_programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora programada'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='ronda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ronda'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='torneos.torneo', verbose_name='Torneo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='cuota_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cuota de inscripción en fichas'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto para inscripciones'), ('En Curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Abierto', max_length=20, verbose_name='Estado del torneo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='torneos', to='torneos.videojuego', verbose_name='Videojuego'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del torneo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='premios',
            field=models.CharField(help_text='Ejemplo: 70% al 1er lugar, 30% al 2do', max_length=200, verbose_name='Premios'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(max_length=50, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen_portada',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del videojuego'),
        ),
        migrations.DeleteModel(
            name='Transmision',
        ),
    ]
