# Generated by Django 6.0.7 on 2026-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_remove_inscripcion_transaccion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='premios',
        ),
        migrations.AddField(
            model_name='torneo',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=16, verbose_name='Cupo máximo de equipos'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fecha_inicio_primera_ronda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de la primera ronda'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto para inscripciones'), ('Lleno', 'Lleno / En espera'), ('En Curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Abierto', max_length=20, verbose_name='Estado del torneo'),
        ),
    ]
