# Generated by Django 6.1.1 on 2026-09-24 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_remove_equipo_torneo'),
        ('torneos', '0005_refactor_competitive_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='numero_partida',
            field=models.PositiveIntegerField(default=1, help_text='Posición de la partida dentro de su ronda.', verbose_name='Número de partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_como_local', to='equipos.equipo', verbose_name='Equipo local'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_como_visitante', to='equipos.equipo', verbose_name='Equipo visitante'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto para inscripciones'), ('Lleno', 'Lleno / En espera'), ('Cerrado', 'Cerrado'), ('En Curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Abierto', max_length=20, verbose_name='Estado del torneo'),
        ),
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.UniqueConstraint(fields=('torneo', 'ronda', 'numero_partida'), name='torneo_ronda_numero_partida_unico'),
        ),
    ]
