# Generated by Django 6.1.1 on 2026-09-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0006_partida_numero_partida_alter_partida_equipo_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='videojuegos/', verbose_name='Imagen de portada'),
        ),
    ]
