# Generated by Django 6.1.1 on 2026-09-24 03:27

from django.db import migrations, models


def migrar_estados_pago(apps, schema_editor):
    Inscripcion = apps.get_model('torneos', 'Inscripcion')
    Inscripcion.objects.filter(estado_pago='Completado').update(estado_pago='Pagado')
    Inscripcion.objects.filter(estado_pago='Fallido').update(estado_pago='Rechazado')


def revertir_estados_pago(apps, schema_editor):
    Inscripcion = apps.get_model('torneos', 'Inscripcion')
    Inscripcion.objects.filter(estado_pago='Pagado').update(estado_pago='Completado')
    Inscripcion.objects.filter(estado_pago='Rechazado').update(estado_pago='Fallido')


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0007_alter_videojuego_imagen_portada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='cuota_inscripcion',
            new_name='cuota',
        ),
        migrations.RunPython(
            migrar_estados_pago,
            revertir_estados_pago,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado del pago'),
        ),
    ]
