# Generated by Django 6.1.1 on 2026-09-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0008_remove_torneo_cuota_inscripcion_torneo_cuota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='cuota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cuota del torneo'),
        ),
    ]
