# Generated by Django 6.1.1 on 2026-09-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0009_alter_torneo_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='detalle_disputa',
            field=models.TextField(blank=True, verbose_name='Detalle de la disputa'),
        ),
        migrations.AddField(
            model_name='partida',
            name='en_disputa',
            field=models.BooleanField(default=False, verbose_name='En disputa'),
        ),
    ]
