# Generated by Django 6.1.1 on 2026-09-25 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0010_partida_detalle_disputa_partida_en_disputa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecompensaPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_otorgada', models.IntegerField(verbose_name='XP otorgada')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to='torneos.partida', verbose_name='Partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_partida', to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'recompensa de partida',
                'verbose_name_plural': 'recompensas de partida',
                'constraints': [models.UniqueConstraint(fields=('partida', 'usuario'), name='recompensa_partida_usuario_unica')],
            },
        ),
    ]
