# Generated by Django 6.1.1 on 2026-09-27 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0011_recompensapartida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='es_bye',
            field=models.BooleanField(default=False, help_text='Indica que el equipo avanzó sin rival en esta ronda.', verbose_name='Avance automático'),
        ),
        migrations.CreateModel(
            name='EventoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_anterior', models.PositiveIntegerField(verbose_name='Rating anterior')),
                ('rating_nuevo', models.PositiveIntegerField(verbose_name='Rating nuevo')),
                ('delta', models.IntegerField(verbose_name='Variación')),
                ('resultado', models.CharField(max_length=10, verbose_name='Resultado')),
                ('algoritmo', models.CharField(default='elo-v1', max_length=20, verbose_name='Algoritmo')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_rating', to='torneos.partida', verbose_name='Partida')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_rating', to='torneos.torneo', verbose_name='Torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_rating', to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'evento de rating',
                'verbose_name_plural': 'eventos de rating',
                'constraints': [models.UniqueConstraint(fields=('partida', 'usuario'), name='evento_rating_partida_usuario_unico')],
            },
        ),
    ]
