# Generated by Django 6.1 on 2026-09-27 22:31

import LeBrum.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0012_partida_es_bye_eventorating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='evidencia_victoria',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias_partidas/', validators=[LeBrum.validators.validate_image_upload], verbose_name='Evidencia de victoria'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='videojuegos/', validators=[LeBrum.validators.validate_image_upload], verbose_name='Imagen de portada'),
        ),
    ]
