# Generated by Django 6.1 on 2026-09-27 22:45

import LeBrum.storage
import LeBrum.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0013_alter_partida_evidencia_victoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='evidencia_victoria',
            field=models.ImageField(blank=True, null=True, storage=LeBrum.storage.PrivateMediaStorage(), upload_to='evidencias_partidas/', validators=[LeBrum.validators.validate_image_upload], verbose_name='Evidencia de victoria'),
        ),
    ]
