# Generated by Django 6.0.7 on 2026-07-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol_plataforma',
            field=models.CharField(choices=[('Dueño', 'Dueño de la Plataforma'), ('Admin', 'Administrador'), ('Jugador', 'Jugador')], default='Jugador', max_length=20),
        ),
    ]
