# Generated by Django 6.0.7 on 2026-08-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saldo_fichas',
            field=models.IntegerField(default=0, verbose_name='Saldo de Fichas LeBrum'),
        ),
    ]
