# Generated by Django 6.0.7 on 2026-08-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_saldo_fichas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tag_jugador',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Tag de Jugador'),
        ),
    ]
