# Generated by Django 6.0.7 on 2026-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_tag_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='riot_id',
            field=models.CharField(blank=True, help_text='Tu Riot ID (ej: Nombre#TAG).', max_length=50, null=True, verbose_name='Riot ID'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='steam_id',
            field=models.CharField(blank=True, help_text='Tu Steam ID64 (17 dígitos).', max_length=50, null=True, verbose_name='Steam ID'),
        ),
    ]
