# Generated by Django 6.0.7 on 2026-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_riot_id_usuario_steam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.URLField(blank=True, default='', help_text='URL de la imagen de perfil. Déjala vacía para usar la imagen por defecto.', verbose_name='Avatar (URL)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_personalizado',
            field=models.CharField(blank=True, default='Listo para la batalla', max_length=60, verbose_name='Estado Personalizado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntos_xp',
            field=models.IntegerField(default=0, verbose_name='Puntos XP (Rango DeLaBruma)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titulo_equipado',
            field=models.CharField(blank=True, default='NOVATO', max_length=30, verbose_name='Título Equipado'),
        ),
    ]
