# Generated by Django 6.0.7 on 2026-08-09 08:40

from django.db import migrations, models


def actualizar_titulos_antiguos(apps, schema_editor):
    """Mueve los títulos legado ('NOVATO') al nuevo equipable por defecto."""
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(titulo_equipado='NOVATO').update(titulo_equipado='NOVATO DE LA BRUMA')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_avatar_usuario_estado_personalizado_and_more'),
    ]

    operations = [
        # Renombra estado_personalizado -> estado_equipado conservando los datos
        migrations.RenameField(
            model_name='usuario',
            old_name='estado_personalizado',
            new_name='estado_equipado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_equipado',
            field=models.CharField(blank=True, default='Listo para la batalla', max_length=60, verbose_name='Estado Equipado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_conexion',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('EN BUSQUEDA', 'EN BUSQUEDA'), ('EN BATALLA', 'EN BATALLA'), ('OFFLINE', 'OFFLINE')], default='ONLINE', max_length=20, verbose_name='Estado de Conexión'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulo_equipado',
            field=models.CharField(blank=True, default='NOVATO DE LA BRUMA', max_length=40, verbose_name='Título Equipado'),
        ),
        migrations.RunPython(actualizar_titulos_antiguos, migrations.RunPython.noop),
    ]
