# Generated by Django 6.0.7 on 2026-08-10 01:47

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuario_estado_personalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fondo_perfil',
            field=models.CharField(choices=[('galaxia', 'Galaxia DeLaBruma'), ('carbono', 'Carbono Neón'), ('neon-cyan', 'Distrito Cian'), ('magenta', 'Sector Magenta'), ('zona-roja', 'Zona Roja')], default='galaxia', max_length=30, verbose_name='Fondo de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='riot_id',
            field=models.CharField(blank=True, help_text='Tu Riot ID en formato Nombre#Etiqueta (ej: Legión#777).', max_length=50, null=True, validators=[usuarios.models.validar_riot_id], verbose_name='Riot ID'),
        ),
    ]
