# Generated by Django 6.1.1 on 2026-09-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_fondo_perfil_alter_usuario_riot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='derrotas',
            field=models.PositiveIntegerField(default=0, verbose_name='Derrotas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='victorias',
            field=models.PositiveIntegerField(default=0, verbose_name='Victorias'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del jugador.', null=True, upload_to='avatares/', verbose_name='Avatar'),
        ),
    ]
