# Generated by Django 6.1.1 on 2026-09-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_derrotas_usuario_victorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fondo_perfil',
            field=models.CharField(choices=[('carbono', 'Carbono Neón'), ('asfalto', 'Asfalto Industrial'), ('rejilla-industrial', 'Rejilla Industrial'), ('scanlines', 'Scanlines')], default='carbono', max_length=30, verbose_name='Fondo de Perfil'),
        ),
    ]
