# Generated by Django 6.1.1 on 2026-09-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_usuario_fondo_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='texto',
            new_name='mensaje',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url_destino',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
