# Generated by Django 6.1.1 on 2026-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_rename_texto_notificacion_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rating_competitivo',
            field=models.PositiveIntegerField(default=1000, help_text='Rating ELO global del jugador.', verbose_name='Rating competitivo'),
        ),
    ]
