# Generated by Django 6.1 on 2026-09-27 22:31

import LeBrum.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_rating_competitivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del jugador.', null=True, upload_to='avatares/', validators=[LeBrum.validators.validate_image_upload], verbose_name='Avatar'),
        ),
    ]
