# Generated by Django 6.1 on 2026-10-05 03:03

import LeBrum.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_solicitudprivacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner_perfil',
            field=models.ImageField(blank=True, help_text='Imagen horizontal que aparece en el podio y en el perfil.', null=True, upload_to='banners_perfil/', validators=[LeBrum.validators.validate_image_upload], verbose_name='Banner de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='kda',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ratio KDA competitivo registrado para el jugador.', max_digits=6, verbose_name='KDA'),
        ),
    ]
