# Generated by Django 6.0.7 on 2026-07-24 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='capitan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipos_capitaneados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_unidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='miembroequipo',
            unique_together={('equipo', 'usuario')},
        ),
    ]
