# Generated by Django 6.0.7 on 2026-08-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='miembroequipo',
            name='rol',
        ),
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modo',
            field=models.CharField(choices=[('5v5', '5v5'), ('2v2', '2v2'), ('1v1', '1v1')], default='5v5', max_length=10, verbose_name='Modo de competición'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='videojuego',
            field=models.CharField(choices=[('CS', 'Counter-Strike'), ('LoL', 'League of Legends'), ('Valorant', 'Valorant')], default='Valorant', max_length=20, verbose_name='Videojuego'),
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='es_capitan',
            field=models.BooleanField(default=False, verbose_name='Es capitán'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='capitan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipos_capitaneados', to=settings.AUTH_USER_MODEL, verbose_name='Capitán'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='equipos.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_unidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
