# Generated by Django 6.0.7 on 2026-08-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_equipo_logo_url_remove_miembroequipo_rol_and_more'),
        ('torneos', '0003_remove_torneo_premios_torneo_cupo_maximo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='videojuego',
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='torneos.torneo', verbose_name='Torneo'),
        ),
    ]
