# Generated by Django 6.0.7 on 2026-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_remove_equipo_modo_remove_equipo_videojuego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='modo',
            field=models.CharField(choices=[('5v5', '5v5'), ('2v2', '2v2'), ('1v1', '1v1')], default='5v5', max_length=10, verbose_name='Modo'),
        ),
    ]
