# Generated by Django 6.0.7 on 2026-08-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_equipo_modo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='banner',
            field=models.URLField(blank=True, null=True, verbose_name='Banner de la Crew'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Siglas oficiales de la crew (ej: [DLB]).', max_length=12, verbose_name='Tag oficial'),
        ),
    ]
