# Generated by Django 6.1.1 on 2026-09-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_remove_equipo_torneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/logos/', verbose_name='Logo'),
        ),
    ]
