# Generated by Django 6.1 on 2026-09-27 22:31

import LeBrum.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_alter_equipo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/logos/', validators=[LeBrum.validators.validate_image_upload], verbose_name='Logo'),
        ),
    ]
