# Generated by Django 6.0.7 on 2026-07-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_mensaje', models.TextField()),
                ('url_adjunto', models.URLField(blank=True, help_text='Captura extra del usuario', null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Pago', 'Problema de Pago'), ('Toxicidad', 'Comportamiento Tóxico'), ('Disputa', 'Disputa de Resultado'), ('Otro', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En Revision', 'En Revisión'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
